---
title: "Performance of linking graduates to researchers"
author: "Flavio & Christoph"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  pdf_document:
    toc: true
    toc_depth: 3
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
set.seed(1234)
```

```{r, echo = FALSE, include = FALSE}
packages <- c("tidyverse", "broom", "dbplyr", "RSQLite", "ggplot2")

lapply(packages, library, character.only = TRUE)

datapath <- "/mnt/ssd/"
db_file  <- paste0(datapath, "AcademicGraph/AcademicGraph.sqlite")
select_fields <- c("physics", "biology", "chemistry", "sociology",
                    "economics", "political science", "psychology", 
                    "mathematics", "geography", "geology", "engineering",
                    "computer science", "environmental science") # fields currently matched 

# ## db connection
con <- DBI::dbConnect(RSQLite::SQLite(), db_file)
cat("The database connection is: \n")
src_dbi(con)
```

## Overview

### SQL example for sourcing number of authors with same name 

```sql 
select * 
from author_sample
inner join (
    select authorid, normalizedname, papercount, citationcount
    from authors 
    where normalizedname = "lawrence b slobodkin"
) using (authorid)
inner join (
    select authorid, fieldofstudyid
    from author_fields 
    where fieldclass = "first"
) using (authorid)
```

```{r, include = FALSE}
field_names_id <- tbl(con, sql(paste0(
    "SELECT FieldOfStudyId, NormalizedName
    FROM FieldsOfStudy
    WHERE Level = 0 
        AND NormalizedName IN (", 
        paste0(paste0("'", select_fields, "'"), collapse = ", "),
        ")"
)))
field_names_id <- collect(field_names_id)

query_proquest <- paste0(
 "SELECT goid
            , year
            , firstname 
            , lastname
            , CASE TRIM(SUBSTR(middle_lastname, 1, l_fullname-l_firstname-l_lastname - 1)) 
                WHEN 
                    '' THEN NULL 
                    ELSE TRIM(SUBSTR(middle_lastname, 1, l_fullname-l_firstname-l_lastname - 1)) 
                END AS middlename
            , fieldofstudy
            , mag_field0
    FROM (
        SELECT goid
            , degree_year AS year 
            , fullname 
            , SUBSTR(TRIM(fullname),1,instr(trim(fullname)||' ',' ')-1) AS firstname
            , REPLACE(fullname, RTRIM(fullname, REPLACE(fullname, ' ', '')), '') AS lastname 
            , TRIM(SUBSTR(fullname, length(SUBSTR(TRIM(fullname),1,instr(trim(fullname)||' ',' ')-1)) + 1)) AS middle_lastname 
            , length(fullname) AS l_fullname 
            , length(SUBSTR(TRIM(fullname),1,instr(trim(fullname)||' ',' ')-1) ) AS l_firstname
            , length(REPLACE(fullname, RTRIM(fullname, REPLACE(fullname, ' ', '')), '')) AS l_lastname
            , fieldname AS fieldofstudy
            , mag_field0
            , university_id
        FROM pq_authors 
        INNER JOIN (
            SELECT goid, fieldname, mag_field0
            FROM pq_fields_mag
            WHERE mag_field0 IN (",
            paste0(field_names_id$FieldOfStudyId, collapse = ', '),
            ") 
        ) USING (goid)
        INNER JOIN (
            SELECT university_id
            FROM pq_unis
            WHERE location like '%United States%'
        ) USING(university_id)
)
WHERE year >= 1985 and year <= 2005 AND length(firstname) > 1
")

query_mag <- paste0(
 "SELECT AuthorId
        , year
        , firstname
        , lastname
        , CASE TRIM(SUBSTR(middle_lastname, 1, l_fullname-l_firstname-l_lastname - 1)) 
            WHEN 
                '' THEN NULL 
                ELSE TRIM(SUBSTR(middle_lastname, 1, l_fullname-l_firstname-l_lastname - 1)) 
            END as middlename 
        , fieldofstudy
        , mag_field0 
    FROM (
        SELECT a.AuthorId
            , a.YearFirstPub AS year
            , a.FirstName AS firstname
            , REPLACE(b.NormalizedName, RTRIM(b.NormalizedName, REPLACE(b.NormalizedName, ' ', '')), '') AS lastname 
            , TRIM(SUBSTR(b.NormalizedName, length(a.FirstName) + 1)) AS middle_lastname 
            , length(b.NormalizedName) as l_fullname 
            , length(a.FirstName) as l_firstname
            , length(REPLACE(b.NormalizedName, RTRIM(b.NormalizedName, REPLACE(b.NormalizedName, ' ', '')), '')) as l_lastname
            , e.NormalizedName AS fieldofstudy
            , e.ParentFieldOfStudyId as mag_field0
        FROM author_sample AS A 
        INNER JOIN (
            SELECT AuthorId, NormalizedName
            FROM Authors
        ) AS b USING(AuthorId)
        INNER JOIN (
            SELECT AuthorId, NormalizedName, ParentFieldOfStudyId
            FROM author_fields c
            INNER JOIN (
                SELECT FieldOfStudyId, NormalizedName
                FROM FieldsOfStudy
            ) AS d USING(FieldOfStudyId)
            INNER JOIN (
                SELECT ParentFieldOfStudyId
                    , ChildFieldOfStudyId
                    , ParentFieldOfStudyId 
                FROM crosswalk_fields
                WHERE ParentLevel = 0
                    AND ParentFieldOfStudyId IN (",
                         paste0(field_names_id$FieldOfStudyId, collapse = ", "),
                    ")
            ) AS e ON (e.ChildFieldOfStudyId = c.FieldOfStudyId)
            WHERE FieldClass = 'first'
        ) AS e USING(AuthorId)
    )
WHERE year >= 1980 and year <= 2010 AND length(firstname) > 1
")

```

```{r, include = FALSE}
linked_ids <- tbl(con, "linked_ids") 
linking_info <- tbl(con, "linking_info") %>%
    filter(mergemode == "1:1" & keywords == "False")
pq_authors <- tbl(con, sql(query_proquest))
mag_authors <- tbl(con, sql(query_mag))

```

```{r, include = FALSE}
mag_authors <- collect(mag_authors)
linked_ids <- collect(linked_ids)
linking_info <- collect(linking_info)
pq_authors <- collect(pq_authors)
```

### Which linking iterations to keep?

```{r}
keep_iteration_ids <- linking_info %>%
    filter(field %in% select_fields) %>%
    pull(iteration_id)
linked_ids <- linked_ids %>%
    filter(iteration_id %in% keep_iteration_ids)
```


```{r, include = FALSE}
d_links <- linked_ids %>%
    left_join(mag_authors %>%
                select(AuthorId,
                        year_mag = year,
                        firstname_mag = firstname,
                        lastname_mag = lastname,
                        field_mag = fieldofstudy,
                        field0_mag = mag_field0),
                by = "AuthorId") %>%
    left_join(pq_authors %>%
                select(goid,
                        year_pq = year,
                        firstname_pq = firstname,
                        lastname_pq = lastname,
                        field_pq = fieldofstudy,
                        field0_pq = mag_field0),
                by = "goid")


d_links <- d_links %>%
    mutate(year_diff = year_mag - year_pq,
            same_firstname = ifelse(firstname_mag == firstname_pq, 1, 0),
            same_lastname = ifelse(lastname_mag == lastname_pq, 1, 0)) %>%
    left_join(field_names_id %>% 
                rename(main_field = NormalizedName),
              by = c("field0_pq" = "FieldOfStudyId"))

d_links <- d_links %>%
    filter(goid != 305107842) # this is some author which was linked but should not have been in pq data; unclear why.


d_links <- d_links %>%
    filter(link_score >= 0.5) %>%
    filter(year_diff >= -5 & year_diff <= 5)
```



## Some histograms 
### link score by field 
```{r, echo = FALSE}
d_links %>%
    mutate(cohort = 10 * floor(year_pq / 10)) %>%
    ggplot(aes(x = link_score)) +
    geom_histogram(aes(y = ..density..),
                    position = position_dodge()) +
    theme(legend.position = "bottom") +
    facet_wrap(~cohort) 
```

### Year between first pub and graduation 
```{r, echo = FALSE}
d_links %>%
    mutate(cohort = 10 * floor(year_pq / 10)) %>%
    ggplot(aes(x = year_diff, fill = main_field, group = main_field)) +
    geom_histogram(aes(y = ..density..), position = position_dodge()) +
    theme(legend.position = "bottom") +
    facet_wrap(~cohort) +
    geom_vline(xintercept = 0, linetype = "dashed", color = "grey30") +
    labs(x = "Year first pub. - Year graduation")
```


## First and last name matches by cohort and field
```{r, echo = FALSE}
d_links %>%
    mutate(cohort = floor(year_pq / 5) * 5) %>%
    group_by(cohort, main_field) %>%
    summarise(across(all_of(c("same_firstname", "same_lastname")),
                     ~mean(.x))) %>%
    gather(key = name, value = val, -cohort, -main_field) %>%
    mutate(name = gsub("same_|name", "", name)) %>%
    ggplot(aes(x = cohort, y = val,
                color = main_field,
                linetype = name)) +
    geom_line() +
    theme(legend.position = "bottom") +
    labs(y = "Fraction of links with same first/last name") +
    guides(color = "none")
```




## How do fields of ProQuest map into fields in MAG?
```{r, echo = FALSE}
dtemp <- d_links %>%
    mutate(grp_year = ifelse(year_pq > 1980, ">1980", "<=1980")) %>%
    group_by(main_field, field_mag, field_pq) %>%
    summarise(nb = n(),
                link_score = mean(link_score),
                .groups = "drop") %>%
    group_by(main_field, field_mag) %>%
    mutate(s = nb / sum(nb)) %>%
    # keep only top 10 fields in mag
    group_by(main_field) %>%
    arrange(desc(nb)) %>%
    mutate(rk = row_number()) %>%
    filter(rk <= 30)

map(.x = select_fields,
    .f = ~dtemp %>%
        filter(main_field == .x) %>%
        ggplot(aes(x = field_mag, y = field_pq)) +
        geom_tile(aes(fill = s)) +
        theme(legend.position = "bottom",
            axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)) +
        labs(title = "Fraction of field ProQuest into field MAG",
            subtitle = paste0("Field: ", .x)) +
        scale_fill_gradient2(low = "red", mid = "yellow", high = "blue",
                midpoint = quantile(dtemp$s, 0.5))
    )

```


## Fraction matched by year and field 
```{r, echo = FALSE}
d_matched <- pq_authors %>%
    left_join(field_names_id %>%
                rename(main_field = NormalizedName),
              by = c("mag_field0" = "FieldOfStudyId")) %>%
    mutate(link = ifelse(goid %in% linked_ids$goid, "linked", "not linked")) %>%
    group_by(year, main_field, link) %>%
    summarise(nb = n(), .groups = "drop") %>%
    group_by(year, main_field) %>%
    mutate(s = nb / sum(nb)) %>%
    ungroup() %>%
    filter(link == "linked")

d_matched %>%
    ggplot(aes(x = year, y = s, linetype = main_field)) +
    geom_line() +
    theme(legend.position = "bottom") +
    labs(y = "Fraction matched")
``` 


```{r, include = FALSE}
DBI::dbDisconnect(con)
```

