---
title: "Performance of linking graduates"
author: "Flavio & Christoph & Mona"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  pdf_document:
    toc: true
    toc_depth: 3
---
This script makes some plots of the links. But not all fields complete

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
set.seed(1234)
```

```{r, echo = FALSE, include = FALSE}
packages <- c("tidyverse", "broom", "dbplyr", "RSQLite", "ggplot2", "stringdist", "knitr") 

lapply(packages, library, character.only = TRUE)

datapath <- "/mnt/ssd/"
db_file  <- paste0(datapath, "AcademicGraph/AcademicGraph.sqlite")


 select_fields <- c("biology",
                    "business",
                    "chemistry",
                    "computer science" ,
                    "economics",
                    "engineering",
                    "environmental science",
                    "geography",
                    "geology" ,
                    "history",
                    "materials science",
                    "mathematics",
                    "physics",
                    "political science",
                    "philosophy",
                    "psychology" ,
                    "sociology") # art, medicine linked but not included yet
```

```{r}
# ## db connection
con <- DBI::dbConnect(RSQLite::SQLite(), db_file)
cat("The database connection is: \n")
src_dbi(con)
```


```{r}
 # Function to process the data for a specific field
# Fields to process
# missing fields: ""art, "chemistry", "geography", "history", "mathematics","medicine", "sociology"


fields_to_process <- c("biology", "business", "computer science", "economics", "engineering", "environmental science", "geology", "materials science", "philosophy", "physics", "political science", "psychology")

# Loop through the fields

process_data <- function(field) {
  
  # Read the data for the specified field
  
  links_graduates_mona <- read.csv(paste0("/mnt/ssd/linked_ids_temp/links_graduates_", field, "_mona_degree0_19852015.csv")) %>%
    rename(authorid_mona = grantid_authorposition) %>%
    rename(goid = AuthorId) %>%
    rename(linkscore_mona=link_score)

  if (field %in% c("biology", "computer science","economics", "engineering", "environmental science", "geology", "physics", "political science", "psychology")) {
  links_graduates_christoph <- read.csv(paste0("/mnt/ssd/linked_ids_temp/links_graduates_", field, "_christoph_fielddegree0.csv")) %>%
    rename(authorid_christoph = AuthorId) %>%
    rename(linkscore_christoph=link_score) 
  } else {
  links_graduates_christoph <- read.csv(paste0("/mnt/ssd/linked_ids_temp/links_graduates_", field, "_christoph_degree0_19852015.csv")) %>%
    rename(authorid_christoph = AuthorId) %>%
    rename(linkscore_christoph=link_score)     
  }    
      

links_graduates_mona <- collect(links_graduates_mona)
links_graduates_christoph <- collect(links_graduates_christoph)

# Performs the full join: bothlink=1 if same authorID assigned in both, 0 if different authorID assigned
# Then calculates the share of links found by Christoph also found by Mona (number links found by both divided by number of links found by Christoph) (share_bothlink)

links_graduates <- links_graduates_mona %>%
  full_join(links_graduates_christoph, by = c("goid")) %>%
  mutate(
    field = field,
    monalink = ifelse(!is.na(authorid_mona), 1, 0),
    chrislink = ifelse(!is.na(authorid_christoph), 1, 0),
    bothlink = ifelse(is.na(authorid_christoph) | is.na(authorid_mona),
                      NA,
                      ifelse(authorid_christoph == authorid_mona, 1, 0)),
     share_bothlink = sum(bothlink == 1 & chrislink == 1, na.rm = TRUE) / sum(chrislink == 1, na.rm = TRUE)
  )

# Look closer at link differences: 
# share of ProQuest goids assigned to same AuthorId (share_sameauthor), distinct AuthorId (share_diffauthor), or missing (share_missing) in one of the two linkings


links_graduates <- links_graduates %>%
 mutate(
    share_sameauthor = sum(bothlink == 1, na.rm = TRUE) / n_distinct(goid),
    share_diffauthor = sum(bothlink == 0 & !is.na(bothlink), na.rm = TRUE) / n_distinct(goid),
    share_missing = sum(is.na(bothlink)) / n_distinct(goid),
    share_missing_mona = sum(is.na(bothlink) & monalink == 0) / n_distinct(goid),
    share_missing_chris = sum(is.na(bothlink) & chrislink == 0) / n_distinct(goid)
 ) 

# Select the desired fields for the table
shares_table <- links_graduates %>%
  select(field, share_bothlink, share_sameauthor, share_diffauthor, share_missing)

# To do: Display the table using kable: not yet working when using the loop

cat(paste0("## ", field, ":\n"))
kable(head(shares_table,1), format = "markdown")

# Select the shares for the bar chart: total number of goids as base

shares_data <- links_graduates %>%
  summarise(
    share_sameauthor = mean(share_sameauthor, na.rm = TRUE),
    share_diffauthor = mean(share_diffauthor, na.rm = TRUE),
    share_missing = mean(share_missing, na.rm = TRUE)
  ) %>%
  gather(variable, value)

# Create the bar chart
bar_chart <- ggplot(shares_data, aes(x = variable, y = value, fill = variable)) +
  geom_bar(stat = "identity", width = 0.7) +
  theme_minimal() +
  labs(
    x = NULL,
    y = "Fraction",
    title = paste("Fraction of ProQuest goids based on assignment of AuthorID  for",field),
    fill= NULL
  ) +
  scale_x_discrete(labels = c("different author ID", " author ID missing", "same author ID"))


# Print the bar chart
print(bar_chart)
} 

for (field in fields_to_process) {
  process_data(field)
  cat("\n\n")
}  
```



```{r, include = FALSE}
DBI::dbDisconnect(con)
```


